# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-2'

menu:
- {name: 'Documentation',      url: 'documentation'}
- {name: 'Bio materials',      url: 'Biomaterials'}
- {name: 'Digital materials',  url: 'digital-materials'}
- {name: 'Garment designs',    url: 'garment-designs'}
- {name: 'About',           url: 'about'}
- {name: 'Contact',            url: 'contact'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'barcode', link:    'https://laurafreyaweller.myportfolio.com/about-me'}
- {icon: 'linkedin', link:   'https://www.linkedin.com/in/laura-weller-82aa5326a/'}
- {icon: 'instagram', link:  'https://www.instagram.com/lauraweller/'}
- {icon: 'envelope', link:   'laurafreyaweller@gmail.com'}

# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
